AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'parse-tweets

  Sample SAM Template for parse-tweets

  '
Globals:
  Function:
    Timeout: 3
Resources:
  TweetsStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
  TweetsProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tweets.parse_and_save
      Runtime: ruby2.5
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Tweets
      Environment:
        Variables:
          DDB_TABLE:
            Ref: Tweets
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream:
              Fn::GetAtt:
              - TweetsStream
              - Arn
            StartingPosition: TRIM_HORIZON
            BatchSize: 25
      CodeUri: s3://tweets-stream/b7fb73f85113b633e6d4c345f4fa6f1f
  Tweets:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
Outputs:
  TweetsProcessor:
    Description: Parse and SaveTweets
    Value:
      Fn::GetAtt:
      - TweetsProcessor
      - Arn
